### ISSUE TITLE
Add additional testimonials to carousel

### ISSUE THREAD

**Issue by metmajer** [getcloudnative/website#11]
Add the recommendations given at https://www.linkedin.com/in/metmajer/ to the carousel inside the "What People Say" section. The contents of the carousel should be configurable through variables in the site's `config.toml`.

**Comment by tomheller** [comment]
I can make the recommendations configurable through the `config.toml`. 
Unfortunately I do not have a linkedin account.
I will prepare the data and let you fill in the recommendations.
