### ISSUE TITLE
Redirect getcloudnative.netlify.com to getcloudnative.io

### ISSUE THREAD

**Issue by metmajer** [getcloudnative/website#2]
For SEO reasons, create a redirect rule in `_redirects` to redirect from `getcloudnative.netlify.com` to `getcloudnative.io`.

Example without HTTPS:
```
# Redirect default Netlify subdomain to primary domain
http://getcloudnative.netlify.com/* http://getcloudnative.io/:splat 301!
```

More information can be found in the Netlify documentation on [Redirect and Rewrite Rules](https://www.netlify.com/docs/redirects/).

**Comment by metmajer** [comment]
@tomheller do you which would be the right directory to place Netlify's `_redirect` file in? Here would be the full content to avoid content duplication:

```
# Redirect Netlify's getcloudnative subdomain to primary domain
http://getcloudnative.netlify.com/* http://getcloudnative.io/:splat 301!
https://getcloudnative.netlify.com/* https://getcloudnative.io/:splat 301!

# Redirect www subdomain to primary domain
http://www.getcloudnative.io/* http://getcloudnative.io/:splat 301!
https://www.getcloudnative.io/* https://getcloudnative.io/:splat 301!
```

**Comment by tomheller** [comment]
I think it goes directly into the root of either the repository or the output directory. 
If it needs to go into the output directory, we can instruct hugo to processes the file and put it innthe output dir

**Comment by metmajer** [comment]
I've just added `_redirects` to the project's root, but that didn't do the trick. May I assign this to you? Thanks!

**Comment by tomheller** [comment]
The file is now in the right place. During testing, it seemed as if the redirect broke something. I'll have a look at that soon.

**Comment by metmajer** [comment]
It might be worth to note that even before I tried to install `_redirects`, the forwarding of www.getcloudnative.io to getcloudnative.io didn't work anymore. Previously, I had forced HTTPS for the getcloudnative.io domain. I'll open an issue with Netlify to clarify.

**Comment by metmajer** [comment]
Resolved with https://github.com/getcloudnative/website/commit/50c7c0828475699d516f8440f170fb2937df2bb8 and after Netlify support has fixed the certificate to work also for www.
