### ISSUE TITLE
Align Social Icons in the Header to the Right

### ISSUE THREAD

**Issue by metmajer** [getcloudnative/website#33]
Hi @tomheller. Is this doable? It seems too crammed in the middle. Please see the Sketch template.

**Comment by tomheller** [comment]
I'm not quite sure what you mean, they are right aligned in the header right now:

![image](https://user-images.githubusercontent.com/6338434/46917841-9b8fbf80-cfcb-11e8-8b87-bd5bd8afd411.png)

**Comment by metmajer** [comment]
Aah, I see. Well, this must be a flex-box thing then. Items distribute differently on my screen.

<img width="1678" alt="screen shot 2018-10-25 at 09 01 05" src="https://user-images.githubusercontent.com/873565/47481672-a00e7080-d834-11e8-9e00-2ab59c5c296c.png">

**Comment by tomheller** [comment]
Can you give me the screen width and browser at which this behavior appears. Maybe I can reproduce it.

**Comment by metmajer** [comment]
@tomheller I've been able to work out a solution in https://github.com/getcloudnative/website/commit/b04331797652b187dc35a0ffe0b9c921d8ed8bc8.
