### ISSUE TITLE
Add shortcode for testimonial "What people say" section

### ISSUE THREAD

**Issue by tomheller** [getcloudnative/website#35]
The what people say section should be reusable via shortcode or template variable in hugo.

**Comment by tomheller** [comment]
You already can use the `{{< testimonials >}}` shortcode in the content pages. Because the layout of the about us page is a little different to the other single pages, it was not possible to use the shortcode in the layout. 

Let me know if this works for you? I have created a PR that should show the testimonials used in a single blogpost page. #36

**Comment by metmajer** [comment]
Hi @tomheller. I have been experimenting a little with the about us page, hence the make-up has slightly diverged from what people see on the main page (this shouldn't be the case though). Anyway, having the testimonials in a shortcode now works perfectly for my needs. Many thanks!
