### ISSUE TITLE
Fix spacings

### ISSUE THREAD

**Issue by metmajer** [getcloudnative/website#7]
Unify and adjust horizontal and vertical spacings according to the Sketch template.

**Comment by metmajer** [comment]
Based the spacings in #19, here's a (hopefully exhaustive) list of items that need some extra work:

#### Header
- [x] Horizontal spacing between icon and GetCloudnative
(with the latter also demanding a smaller font size in #6)

#### Section: Our Offering
- [x] Vertical spacing between subheaders "Strategy", "Execution", "Enablement" and their respective descriptions

#### Section: Let's Walk the Talk
- [x] Vertical spacing between text and "Say Hello!" button (also the text requires a larger font size in #6)
- [x] The height of the "Say Hello!" button

#### Section: We Deliver Value-Driven Solutions
- [x] Vertical spacing between the section description and "Here are some of the technologies…"
- [x] Vertical spacing between the logos and the "See our blog posts" link

#### Section: What People Say
- [x] Vertical spacing between the section description and the logos
- [x] Vertical spacing between the logos and the quote
- [x] Vertical spacing between the quote and the quotee
- [x] Vertical spacing between the quotee and the "See our projects" link 
- [x] The line-height of the quote

#### Footer
- [x] Line height of link items
- [x] Spacing between bottom-most link item and copyright notice

**Comment by metmajer** [comment]
@tomheller I can still see that the sections have style overrides specified in HTML. Didn't we want to get rid of those to create equal spacings across all sections?

**Comment by tomheller** [comment]
@metmajer yes, that's right. I'm gonna take care of this one.
